### PR TITLE
Docs/port info

### PR DESCRIPTION
**Pull request by tanishqmanuja**

### CODE REVIEW

**Comment by tanishqmanuja** [comment]
Reverted commit from other PR

**Comment by dasshubham762** [comment]
Can you rebase doc update commit [docs: port 5625 disclaimer](https://github.com/dasshubham762/atomberg-integration/pull/15/commits/94707c809677c69196dac4b5148afeab4716b973) over the latest changes?

_To remove the revert commit_

**Comment by tanishqmanuja** [comment]
Squash and merge, will get removed automatically i guess.

Otherwise will rebase in an hour or two.. away from PC right now.

**Comment by dasshubham762** [comment]
Thanks a log

**Pull request merged**
